logging:
    level:
        com.mju.zjj.admin: DEBUG

server:
  port: 8762

spring:
    application:
        name: XLJK-ADMIN
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 2
        host: 127.0.0.1
        jedis:
            pool:
                max-active: 20
    datasource:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/xljk?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
    sleuth:
      enabled: false

mybatis:
  basepackage: com.mju.zjj.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true


#redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: ${REDIS_HOST:127.0.0.1}
    port:  ${REDIS_PORT:6379}
    password:
    timeout: 2000
    # 服务或应用名
    sysName: cloud-admin
    enable: true
    database: 0

config:
  jwt:
    expire: 50000000
    secret: wozhidao
